# Generated by Django 5.1.2 on 2024-10-24 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=250)),
                ('brand_tr', models.CharField(max_length=250, null=True)),
                ('brand_en', models.CharField(max_length=250, null=True)),
                ('image', models.ImageField(upload_to='Brand Image')),
            ],
            options={
                'verbose_name_plural': 'Markalar',
            },
        ),
        migrations.CreateModel(
            name='CaseShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_shape', models.CharField(max_length=250)),
                ('case_shape_tr', models.CharField(max_length=250, null=True)),
                ('case_shape_en', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Kasa Şekilleri',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=250)),
                ('color_tr', models.CharField(max_length=250, null=True)),
                ('color_en', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Renkler',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=250)),
                ('gender_tr', models.CharField(max_length=250, null=True)),
                ('gender_en', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cinsiyetler',
            },
        ),
        migrations.CreateModel(
            name='GlassFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glass_feature', models.CharField(max_length=250)),
                ('glass_feature_tr', models.CharField(max_length=250, null=True)),
                ('glass_feature_en', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cam Özellikleri',
            },
        ),
        migrations.CreateModel(
            name='Mechanism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanism', models.CharField(max_length=250)),
                ('mechanism_tr', models.CharField(max_length=250, null=True)),
                ('mechanism_en', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Mekanizmalar',
            },
        ),
        migrations.CreateModel(
            name='StrapType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strap_type', models.CharField(max_length=250)),
                ('strap_type_tr', models.CharField(max_length=250, null=True)),
                ('strap_type_en', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Kayış Tipleri',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=250)),
                ('style_tr', models.CharField(max_length=250, null=True)),
                ('style_en', models.CharField(max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tarzlar',
            },
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.TextField(blank=True, null=True)),
                ('province', models.CharField(blank=True, max_length=150, null=True)),
                ('district', models.CharField(blank=True, max_length=150, null=True)),
                ('neighbourhood', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Adresler',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=250)),
                ('model_tr', models.CharField(max_length=250, null=True)),
                ('model_en', models.CharField(max_length=250, null=True)),
                ('description', models.TextField()),
                ('description_tr', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='Product Image')),
                ('price', models.FloatField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEticaret.brand')),
                ('case_shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEticaret.caseshape')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEticaret.color')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEticaret.gender')),
                ('glass_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEticaret.glassfeature')),
                ('mechanism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEticaret.mechanism')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('strap_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEticaret.straptype')),
                ('tarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEticaret.style')),
            ],
            options={
                'verbose_name_plural': 'Ürünler',
            },
        ),
        migrations.CreateModel(
            name='BasketProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppEticaret.product', verbose_name='')),
            ],
            options={
                'verbose_name_plural': 'Sepetteki Ürünler',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('birtdate', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profiller',
            },
        ),
    ]
